refactor: Use "-n" argument for test commands instead of "! -z"

diff --git a/.github/actions/latest-docker-repository-version/action b/.github/actions/latest-docker-repository-version/action
--- a/.github/actions/latest-docker-repository-version/action
+++ b/.github/actions/latest-docker-repository-version/action
@@ -1,6 +1,6 @@
 #!/bin/sh -e
 
-test ! -z "${DOCKER_HUB_REPOSITORY}" || ( echo "DOCKER_HUB_REPOSITORY is not defined!" && false )
+test -n "${DOCKER_HUB_REPOSITORY}" || ( echo "DOCKER_HUB_REPOSITORY is not defined!" && false )
 
 RESPONSE="$(curl -sL https://registry.hub.docker.com/v2/repositories/${DOCKER_HUB_REPOSITORY}/tags)"
 
@@ -8,7 +8,7 @@ echo "${RESPONSE}" | jq
 
 LATEST_PUSHED_VERSION="$(echo "${RESPONSE}" | jq -r '.results[].name' | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+' | sed -n '1p' - | tr -d '\n')"
 
-test ! -z "${LATEST_PUSHED_VERSION}" || ( echo "LATEST_PUSHED_VERSION is not found!" && false )
+test -n "${LATEST_PUSHED_VERSION}" || ( echo "LATEST_PUSHED_VERSION is not found!" && false )
 
 echo "::set-output name=version::${LATEST_PUSHED_VERSION}"
 echo "Latest Version: ${LATEST_PUSHED_VERSION}"
